### ISSUE TITLE
"Edit constraints" not opening editing panel

### ISSUE THREAD

**Issue by Joellepeters** [matt-curtis/Fluid-for-Sketch#102]
Clicking "edit constraints" is not actioning anything / bring up an edit panel. 

Version 39.1 (31720)

Edit -- 

After experimenting more with this I discovered it was an issue similar to https://github.com/matt-curtis/Fluid-for-Sketch/issues/98

However, in this case (perhaps due to my dual monitor setup) the panel was completely inaccessible / offscreen. Managed to wrangle it back into the window by switching to a single monitor and messing with the Sketch window size.

**Comment by matt-curtis** [comment]
Hello @Joellepeters, thanks for submitting this one. I'll go ahead and collapse it into #98.
