### ISSUE TITLE
Not available in Sketch 3.91 (31720)

### ISSUE THREAD

**Issue by mischugo** [matt-curtis/Fluid-for-Sketch#103]
Hello,

the plug in is installed, but not available in the plugin list :-(

**Comment by matt-curtis** [comment]
Are you certain? Have you tried restarting Sketch? Try checking Sketch's plugin folder and make sure Fluid is there. Plugins > Manage Plugins > Tiny Cog in the Bottom Left > Show Plugin Folder.

**Comment by mischugo** [comment]
Really. 3 times restating Sketch. Manually delete the plugin, and installed. With toolbox ... Nothing.
Seems to be a bit crazy.
I will try it again with my MacBook at home (home office)

Thanks!

**Comment by matt-curtis** [comment]
Weird, no one has reported this before. There's been problems with Sketch Toolbox before, you may want to try a manual install (see the README).

**Comment by mischugo** [comment]
Hey,

have delete the plug in manualy. Restart maschine. Open Sketch -> get plugins -> download it - and install it. Restart Sketch
- it works -

My be, sometimes apple maschines works like windows - doing a restart could help

Cheers

**Comment by matt-curtis** [comment]
Glad you got it working! :)

**Comment by mischugo** [comment]
Thanks a lot!
