### ISSUE TITLE
Excuse me, I want to take these English into Chinese.How should I do.Can you tell some information?

### ISSUE THREAD

**Issue by ilovebamboo** [matt-curtis/Fluid-for-Sketch#104]
Excuse me, I want to take these English into Chinese.How should I do.Can you tell some information?
![group 2](https://cloud.githubusercontent.com/assets/6214084/18223290/5a408e7e-71e5-11e6-9ab9-633c6968e0ae.png)

**Comment by matt-curtis** [comment]
This isn't possible yet, as Fluid isn't open source, which would make localizations and contributions like this easier. I'm _really_ hoping to push out a new version of Fluid that fixes some bugs and goes open source soon, though. Can I call on you for when that does happen?

Created #105 to express the need for localization.

**Comment by ilovebamboo** [comment]
Thanks for your reply.
