### ISSUE TITLE
sketch 40.3

### ISSUE THREAD

**Issue by n8mills** [matt-curtis/Fluid-for-Sketch#107]
plugin not showing up in plugins dropdown or toolbox.

**Comment by matt-curtis** [comment]
@n8mills Are you sure you've installed the plugin correctly? Just tested in 40.3.

**Comment by n8mills** [comment]
I’ll double check. I unzipped the file and doubled clicked the plugin to install like all the others.

Nathan Mills,  BDes (Hons).

Senior Product Designer

—

Healthcare Human Factors

Toronto General Hospital | UHN

190 Elizabeth St, R. Fraser Elliott Building, 4th Floor

Toronto, Ontario, M5G 2C4, Canada

www.humanfactors.ca

mobile  +1 647-209-6455

**Comment by matt-curtis** [comment]
@n8mills Any updates?

**Comment by n8mills** [comment]
Got it working!

Nathan Mills,  BDes (Hons).

Senior Product Designer

—

Healthcare Human Factors

Toronto General Hospital | UHN

190 Elizabeth St, R. Fraser Elliott Building, 4th Floor

Toronto, Ontario, M5G 2C4, Canada

www.humanfactors.ca

mobile  +1 647-209-6455

**Comment by matt-curtis** [comment]
Great, closing then.
