### ISSUE TITLE
Doesn't work with Sketch 42

### ISSUE THREAD

**Issue by bavarianbytes** [matt-curtis/Fluid-for-Sketch#116]
Is it working with the current version of Sketch?
Tried it on my own and the sketch demo document. Nothing happens.

What i did:
- Gave a textbox constraints on 3 sides as margin to the canvas of an artboard on the symbols page.
- Updated the layout.
- Resized the all layers on the symbols page => nothing happens.
- Resized a placed symbol => nothing happens.

**Comment by matt-curtis** [comment]
Late to the party on this one. Working on a fix.

**Comment by ziyafenn** [comment]
Guys, is it still not working on Sketch 42 with symbol text overriding?

**Comment by ziyafenn** [comment]
And paddings also doesn't work properly. Only useful thing right now is Math expressions in fixed/dynamic width/height.

**Comment by bavarianbytes** [comment]
Switched to Auto-Layout...

**Comment by matt-curtis** [comment]
@ziyafenn @bavarianbytes 

Sorry for the delay on this one. Part of the issue is that I can't replicate the exact issues you're mentioning. Can you explain exactly what you did, what you expected to happen, and what happens instead?

**Comment by matt-curtis** [comment]
@ziyafenn @bavarianbytes Closing until I can get more feedback...
