### ISSUE TITLE
[Feature] Provide Official Support to Instal & Update via Sketchpacks

### ISSUE THREAD

**Issue by luxlogica** [matt-curtis/Fluid-for-Sketch#117]
Please provide official support for [Sketchpacks](https://sketchpacks.com/) - this is a project that deserves it. It allows the Sketch plugin developer to keep all their users automatically updated, with no work from their part - updates are delivered automatically from your GitHub repo, when you push to your 'master' branch.

Please have a look their [integrations page](https://github.com/integration/sketchpacks-relay), so we can get not just automatic version numbering, but also **auto-updating** working!

**Comment by matt-curtis** [comment]
Sounds like a good idea. Will commit this along with the next major version.

**Comment by matt-curtis** [comment]
Done.
