### ISSUE TITLE
No artboard in Toggle Size or in Preview > Resize

### ISSUE THREAD

**Issue by ama5** [matt-curtis/Fluid-for-Sketch#120]
Hi -
I just installed Fluid and I am using Sketch v44. I went about setting up some constraints and have been trying to Resize the artboard in Preview and Toggle Size the artboard in the main window, but in neither case does the menu contain any artboard sizes – just categories. I've tried restarting, disabling all other plug-ins.
Thanks!
![fluid-noart](https://cloud.githubusercontent.com/assets/9553150/26263514/26f9e7c6-3ca7-11e7-9625-8090aca4eb09.png)

**Comment by matt-curtis** [comment]
Fixed in 1.7.5. :)
