### ISSUE TITLE
Plugin not working on Sketch 45?

### ISSUE THREAD

**Issue by adamhugh** [matt-curtis/Fluid-for-Sketch#124]
Tool bar not visible? Nothing working? Installed on different machines running Sketch 45. Happy to provide more info if needed.

Thanks in advance.

**Comment by roobottom** [comment]
I have this issue too. Also happy to provide details if needed.

**Comment by alecmarcus** [comment]
Not working for me either. Updated to 45.1 (43504) just before installing, had never used or installed the plugin before. The plugin installs and key commands are detected, but no dialogue boxes or controls open.

**Comment by moxamax** [comment]
Also having the same issue on 44.1 & macOS 10.12.5. Here are the console logs when toggling toolbar:

` *** Assertion failure in void swizzle(__unsafe_unretained Class, SEL, __strong RSSwizzleImpFactoryBlock)(), /Users/matt/Documents/Development/Xcode Projects/Sketch Plugin Framework/RSSwizzle.m:194`

`Exception: Selector layerSelectionDidChange not found in instance methods of class MSDocument.`

`Selector layerSelectionDidChange not found in instance methods of class MSDocument.`

Hope that'll be helpful.

**Comment by matt-curtis** [comment]
Thanks everyone! New release with 45.1 compatibility is out. Also adds support for native Sketch updates.
