### ISSUE TITLE
toolbar very interesting

### ISSUE THREAD

**Issue by wave2588** [matt-curtis/Fluid-for-Sketch#131]
I find the toolbar in the plugin very interesting.
How did you make it?? 
Have any articles?

**Comment by matt-curtis** [comment]
The toolbar is just an `NSWindow` with a transparent background. The main difference is that it's attached as a 'child window' to the topmost Sketch document window (see `-[NSWindow addChildWindow:ordered:]`), which allows for it to constantly stay just above the current document you're working on.
