### ISSUE TITLE
Rounding to nearest pixel edge

### ISSUE THREAD

**Issue by almonk** [matt-curtis/Fluid-for-Sketch#16]
Amazing work on this plugin. It seems like the preview is blurry on retina displays & would be great to fix that :)

**Comment by matt-curtis** [comment]
Thanks!

This is caused by percentages resolving to sub-pixel values, like 1.5. `Layers > Round to Nearest Pixel Edge` will fix it.

This will probably be implemented in a Settings panel, and the default will be to round the percentages and centering to whole numbers (pixels).
