### ISSUE TITLE
How can I keep aspect ratio of an product picture and flow other content under it?

### ISSUE THREAD

**Issue by lexrus** [matt-curtis/Fluid-for-Sketch#2]
Take an example:
![cook multiline 2x](https://cloud.githubusercontent.com/assets/219689/10902489/a1fe3c9e-8239-11e5-9163-aca4842018ef.jpg)

I haven't figured out a proper way to do that.
Anyway, this plugin is awesome.

**Comment by matt-curtis** [comment]
The easiest way would probably be to lock the proportions, and change only the height of the image in your  constraints.

![constraint_demos_sketch](https://cloud.githubusercontent.com/assets/1414704/10907971/bb5ffe16-81f3-11e5-9341-99c22c7f36bb.png)

I would then put the rest of the content in a group beneath that image, with an appropriate top pinning. Maybe top-pinning = `100% + yourPadding` and relativity = previous sibling?

**Comment by matt-curtis** [comment]
See Issue #5
