### ISSUE TITLE
Floating Constraint Inspector

### ISSUE THREAD

**Issue by matt-curtis** [matt-curtis/Fluid-for-Sketch#23]
Would speed up workflow, and get rid of an extra click.

**Comment by jkfinger** [comment]
**Current Flow for `Edit Constraints`**: 
1. User clicks `Edit Constraints` 
2. Preferences pop up 
3. User sets preferences 
4. User clicks another layer and `Edit Constraints` disappears.  

**Ideal Flow for `Edit Constraints`**: 
1. User clicks `Edit Constraints` 
2. Preferences pop up 
3. User sets preferences 
4. User clicks another layer and `Edit Constraints` autoupdates without closing.
