### ISSUE TITLE
Plugin doesn't work when i switch between sketch-documents

### ISSUE THREAD

**Issue by BasStortelers** [matt-curtis/Fluid-for-Sketch#27]
The error message: "Select an artboard, or any layer in an artboard, so we know which artboard to target."

**Comment by einancunlu** [comment]
This is a general bug in Sketch. Its window focus sometimes corrupts and thinks you on wrong document. To fix this try to open a new Sketch document and close while your actual Sketch document is active on the background.

**Comment by matt-curtis** [comment]
@einancunlu Thanks for the input. How have you seen this bug manifest elsewhere?

Recognized as Issue #4, closing
