### ISSUE TITLE
How to select the layer?

### ISSUE THREAD

**Issue by allenwong** [matt-curtis/Fluid-for-Sketch#3]
<img width="695" alt="2015-11-03 15 10 49" src="https://cloud.githubusercontent.com/assets/698982/10902779/243cb084-823d-11e5-91bb-4c00a4c8c610.png">

**Comment by matt-curtis** [comment]
Looks like you already have a layer selected, so things should be working. What version of Sketch are you running? Does this happen with all documents?

**Comment by matt-curtis** [comment]
I've recognized this as Issue #4. The temporary workaround is to close and reopen the document.
