### ISSUE TITLE
Unable to create constraints on a group & childrens after copy/paste from another document

### ISSUE THREAD

**Issue by EtienneServant** [matt-curtis/Fluid-for-Sketch#31]
When I create a constraint on a group I copied from another document, every layer of this group have the same constraint.

But if I close & reopen Sketch, It works fine.

**Comment by matt-curtis** [comment]
Pretty sure this is caused by #4, which is fixed in the next version

**Comment by EtienneServant** [comment]
@matt-curtis Okay thanks !
