### ISSUE TITLE
Fluid installed but does not respond (Sketch 3.4)

### ISSUE THREAD

**Issue by martinboerma** [matt-curtis/Fluid-for-Sketch#34]
Hi,

I installed plugin via Sketch Toolbox while Sketch was not running. Plugin appears in correct folder and in Sketch menu but does not respond when selecting "Edit constraints" or "Show toolbar".

Sketch version 3.4 (15575)

Cheers,
Martin

**Comment by matt-curtis** [comment]
This is issue #15 - you must install Fluid manually for now.
