### ISSUE TITLE
Dynamic sections

### ISSUE THREAD

**Issue by leinerud** [matt-curtis/Fluid-for-Sketch#43]
I would really like to be able to create "sections" to my designs which can be placed after each other (from top to bottom). Today in Sketch, if a design change is made it often results in that you have to select all other elements and "push them down" on the page.

Functionality:
- A section consists of a unlimited number of other elements (just like a group)
- A section is dynamic in height, so if the height of the section is changed, it pushes the sections below down.
- Each section can be dragged and dropped over/under other sections to sort them from page top to bottom.

**Comment by matt-curtis** [comment]
You can do this currently with the `Previous Sibling` relativity. In the next release, you'll be able to select multiple layers and edit them at once, so you can select multiple 'sections' and set constraints so that you get this stacking behavior.

I can create a demo if you'd like. Let me know if this is what you had in mind.

**Comment by leinerud** [comment]
Nice! But I guess that I don't understand how to use it. I have two rectangles in the same group and I set "Previous sibling" and "top:0" on the second one, but then the second rectangle places itself in the exact same position as the first, but I want the second rectangle to come directly below the first one (+ some padding). How can I do this?

And thank's for the support!

**Comment by matt-curtis** [comment]
You want `top pinning = 100% + your padding`. Percentages are relative to the dimension of the axis they're on, so: 
- using `100%` in the **top and bottom** pinnings equals `100%` of previous sibling's _height_ and
- using `100%` in the **right and left** pinnings equals `100%` of the previous siblings _width_.

It's the same way for Fixed Width/Height as well.

**Comment by leinerud** [comment]
Oh yeah. So great! Thank you.
