### ISSUE TITLE
does it support stack view? apple recommends we use stack views as we can.

### ISSUE THREAD

**Issue by lastcc** [matt-curtis/Fluid-for-Sketch#45]
What apple said in its wwdc was to use the stack view as one can. Although none of its example code uses it maybe in consideration for backward compatibility.

**Comment by matt-curtis** [comment]
Your question is confusing, but I believe issue #43 addresses your concerns, at least partially.

Fluid is not meant to act as a means to use, or model, iOS/OS X controls. It is simply a method for making the sizing and positioning of layers follow a constraint-based layout, _in Sketch_.

**Comment by lastcc** [comment]
well constraints are raw constraints. and the new stack view introduced by apple is a new way to layout views on screen. It is not like a uiview in itself. It's more like a layout guide or a layout rectangle, whose sole purpose is to help make auto layout easier. we all know that when it comes to too many views, the constraints could be too many to adjust one since one constraint can affect many others. Use embedded stack views help reduce constraints needed thus make it much easier when u need to make changes in ui next time.

**Comment by matt-curtis** [comment]
I see. I haven't had a chance to use iOS 9's stack view yet, so I'm a little out of touch there. However, I do see the use a 'stack mode' or 'stacking behavior' would have, and I've been trying to figure out the best way to add something like this.
