### ISSUE TITLE
Suggestion: Pin objects to each other 

### ISSUE THREAD

**Issue by taurean** [matt-curtis/Fluid-for-Sketch#46]
Ideally, I would like to be able to pin an object to maintain certain margin to another object in the artboard. A potential use case would be pinning a button to a certain position within a modal dialog that is dynamic in height and/or width.

**Comment by matt-curtis** [comment]
You can do this now by setting relativity to either Group or Previous Sibling. Unfortunately it's not possible at this time to pin two independent layers to one another. You can find some examples of this in the Constraints Demo document.

Let me know if I can help any other way :)
