### ISSUE TITLE
Toolbar obscures 'message' dialog

### ISSUE THREAD

**Issue by studiostoll** [matt-curtis/Fluid-for-Sketch#49]
we're using a plugin that displays colors used for a selected element as a message (see screenshot) which is in conflict with Fluid's toolbar: the messages are being placed below the toolbar. This is true for any message I guess, which are being used for alerts etc. in numerous plugins. 

I have no idea what's possible, but maybe the "paint order" could be changed, making the toolbar always the lowest layer (since messages usually have more priority)? or making the toolbar position movable?

![image](https://cloud.githubusercontent.com/assets/1927315/11142467/c114af76-89ed-11e5-98c0-184685d070b7.png)

**Comment by matt-curtis** [comment]
There isn't much I can do about this, as the message dialog is at the 'view' level rather than 'window' level. However in v1.7 the toolbar will stay where you put it, so you can just move it out of the way (see #25)

**Comment by studiostoll** [comment]
@matt-curtis cool. how long will it stay?

**Comment by matt-curtis** [comment]
It will stay wherever you move it for as long as sketch is running. Window positions won't persist across sketch restarts

**Comment by studiostoll** [comment]
ok, thanks!
