### ISSUE TITLE
Retina Preview Image

### ISSUE THREAD

**Issue by trevormkay** [matt-curtis/Fluid-for-Sketch#58]
On retina the preview window seems to be @1x and rather blurry,

**Comment by matt-curtis** [comment]
Hmm. There's nothing specifically about the window _itself_ that would cause it to be blurry...do you mean the preview image is blurry?

**Comment by trevormkay** [comment]
Yeah, the preview is blurry

**Comment by matt-curtis** [comment]
Thanks, I've fixed this in the next release.
