### ISSUE TITLE
Improving Preview Mode

### ISSUE THREAD

**Issue by matt-curtis** [matt-curtis/Fluid-for-Sketch#6]
Needs to expand to include:
1. User-defined sizes
2. More common device presets
3. Zooming (?)
4. Export?

**Comment by imcatnoone** [comment]
Thoughts on expansion for Preview Mode:
- Drop down with multiple (common) device presets (iPhones, Tablets, Android, etc.)
- Possibility to attach the preview window to the sketch document so it isn't continually floating around
- Export artboards screens (and potentially individual layers)
- Way to minimize Preview screen (only possible to close and enlarge at the moment)

**Comment by gerrit** [comment]
Exporting bitmaps for different devices directly from the preview would be less useful than being able to generate artboards that can then be fine-tuned manually e.g..

**Comment by matt-curtis** [comment]
You mean being able to insert the 'preview' back into the document?

**Comment by gerrit** [comment]
@matt-curtis yeah exactly. maybe that's a separate function from the preview window, but I found myself copy&pasting constraint-based layouts to different-sized artboards (and then updating them) a lot (and then tweaking them if necessary)
