### ISSUE TITLE
Input field steals focus in background

### ISSUE THREAD

**Issue by andrejilderda** [matt-curtis/Fluid-for-Sketch#61]
Hi Matt,

V. 1.7 is great, thanks for the huge improvement! There's one issue that I've encountered with moving objects though. Here's a way to replicate it:
1. Edit a constraint by changing a value in the input field.
2. Click somewhere on the canvas to make the constraint window disappear.
3. Click an object and try to move it up and down by using the arrow keys ↑ ↓ (doesn't work, also +10px increment by holding shift does not work)

It seems the constraint input field remains focused in the background. With a little luck you can get the keyboard shortcut to work again by changing the relativity a couple sometimes.

Best regards,
Andre

**Comment by matt-curtis** [comment]
Thanks for pointing this out - I've updated the 1.7 build available. Try it and let me know if it fixes the problem.

**Comment by andrejilderda** [comment]
Seems to be fixed. Thank you, Matt! 👍

**Comment by matt-curtis** [comment]
Awesome. Thanks for testing!
