### ISSUE TITLE
Preview window  issue with secondary display

### ISSUE THREAD

**Issue by atillacode** [matt-curtis/Fluid-for-Sketch#62]
Just noticed that i can't focus the Sketch window when the Preview window is focused.
I would love to expand the Preview window to a secondary screen while working on my sketch file, see photo: http://i.imgur.com/wa6wJ1u.jpg

Cheers,
Atilla

**Comment by matt-curtis** [comment]
The Preview Window is actually modal like this intentionally, kind of a technical limitation. I'm working on a solution, but it won't be in 1.7.

**Comment by matt-curtis** [comment]
#65
