### ISSUE TITLE
What is the correct behaviour when used with dynamic text symbols?

### ISSUE THREAD

**Issue by lewisnyman** [matt-curtis/Fluid-for-Sketch#66]
Hi!

I have a symbol that contains dynamic text sub-layers. Fluid would be really useful here as I can set up the margin logic between each sibling and then text wrapping is handled automatically for me when I change the text of any of the sub-layers for each instance of the symbol.

This doesn't seem to work as expected, as Sketch wants to set the position of each sub-layer everywhere, and you can see the elements jumping around as it runs through each instance of that symbol. Is it possible for each Symbol instance to share the Fluid constraints but not share the positioning calculated by Fluid?

**Comment by matt-curtis** [comment]
Unfortunately, this isn't possible as things are now. Sketch has the synchronization of a Symbol's sub-layers hardcoded. The only way to get rid of this behavior is to detach the symbol. #64 would probably help here, but that's a ways off from being implemented. :/
