### ISSUE TITLE
Layout should update itself while resizing artboard / group / sibling.

### ISSUE THREAD

**Issue by avendiart** [matt-curtis/Fluid-for-Sketch#70]
This would be a really nice addition to the plugin, as hitting Update Layout all the time to spot design problems gets frustrating over time. Is this addition at all possible? Huge thanks for the plugin and work you put in it.

**Comment by matt-curtis** [comment]
I had this same idea while developing Fluid. The problem is that:
1. It would require me to do some hacky/dirty things to Sketch
2. There's no good way to discern between when a user would want the layout updated as a result of a resize, and when they wouldn't (except modifier key, maybe?)

**Comment by avendiart** [comment]
1. Isn't it as simple as listening to the resize event (if any?) and triggering the resize?
2. To me that should be the default behaviour with a configuration option to disable it.
