### ISSUE TITLE
Arrow keys & enter/return stop working (Sketch v3.4.4 (17249))

### ISSUE THREAD

**Issue by coryoos** [matt-curtis/Fluid-for-Sketch#71]
After I access the "Preview" mode, or "Toggle Artboard Size" the arrow keys, and enter/return stop working in Sketch. I have to close the app, then reopen. They then begin working again, so I'm thinking Fluid-for-Sketch has something to do with it. Love the plugin!

**Comment by matt-curtis** [comment]
https://twitter.com/arle13/status/679800626197344256 (self note)

**Comment by covall** [comment]
+1

**Comment by keaton-taylor** [comment]
This happens to me in Sketch 3.5.1 as well

**Comment by Robcis** [comment]
I have the exact same issue and it makes me very frustrated because I have to reopen sketch every single time I finish using fluid. It's a pain if you a lot of sketch files open. I'm using Sketch Version 3.5.2 (25235).
