### ISSUE TITLE
Consider open-sourcing MCSketchConstraints, MCSketchPluginFramework, etc.

### ISSUE THREAD

**Issue by romannurik** [matt-curtis/Fluid-for-Sketch#74]
You've done some amazing work; it'd be great to see the Swift/Obj-C code behind all your hackery :)

**Comment by matt-curtis** [comment]
Addressed in part in #47. :)

**Comment by matt-curtis** [comment]
I'll be addressing it in greater detail when the time comes, but I've open-sourced the MCSketchPluginFramework Fluid uses: https://github.com/matt-curtis/Sketch-Plugin-Framework
