### ISSUE TITLE
Preview window not working on Sketch 3.5.1

### ISSUE THREAD

**Issue by CraigShields** [matt-curtis/Fluid-for-Sketch#81]
Hello, thank you for all the work you're putting into this plugin. It's awesome!

I'm running Sketch 3.5.1 and I just cannot get the preview window to work. If I hit 'Preview' (even after selecting an artboard) nothing happens. Any clues?

Thank you!

**Comment by matt-curtis** [comment]
Hello Craig,

Can you get any artboards to work? Have you also made sure that you have the latest version of Fluid installed?

**Comment by CraigShields** [comment]
Hello Matt,

Uninstalling and reinstalling the plugin via Sketch Toolbox did the trick. Thank you!
