### ISSUE TITLE
Core Sketch keyboard shortcuts stop working 

### ISSUE THREAD

**Issue by gabriel-r** [matt-curtis/Fluid-for-Sketch#82]
After using the Fluid panels a few times, the core Sketch keyboard shortcuts would stop working until Sketch is restarted. This affects at least these operations:
- Move with arrows left/right/top/down with focus in the canvas selection, as well as Shift+Up, Shift+Dn, etc.
- Increase or decrease size values with focus on the size inspector with an element in focus.

**Comment by matt-curtis** [comment]
#71
