### ISSUE TITLE
Renaming & resizing layers will completely destroy your design

### ISSUE THREAD

**Issue by Robcis** [matt-curtis/Fluid-for-Sketch#83]
After using Fluid I can't rename my layers because it completely distorts my layout. Everything including the artboard changes size if you rename your layers, even when fluid toolbar is closed. The issue seems to arise when you hit enter after renaming your layers. If you just click on another layer, it does not affect it. Also, the exact same thing happens when you use the element inspector to relocate or to resize your layers. As soon as you hit enter, the whole hell breaks loose. Pressing CMD+Z still applies newly entered settings and also reverts the mess it made. Even though it is a way out of this, it's very bad.  

I'm using Sketch Version 3.5.2 (25235).

**Comment by matt-curtis** [comment]
This is odd, I've never experienced this. It may be a variation of the hotkey issue in #71. Investigating - thanks for making this issue

**Comment by matt-curtis** [comment]
Confirmed as #71. Which has been fixed and will be out as an update soon

**Comment by Robcis** [comment]
Great! Thanks a lot @matt-curtis !
