### ISSUE TITLE
Sketch 3.6 breaks Preview Mode

### ISSUE THREAD

**Issue by bsrz** [matt-curtis/Fluid-for-Sketch#86]
Updated to Sketch 3.6 today.
No longer able to preview artboard, it just keeps on creating new artboards.

**Comment by matt-curtis** [comment]
Fixed by #87. Thanks for letting me know.

**Comment by bsrz** [comment]
@matt-curtis thanks for being so quick to fix this!
![](https://media4.giphy.com/media/D6WuLOKOpR2fK/200w.gif)

**Comment by matt-curtis** [comment]
![Django](https://media.giphy.com/media/RZhmtLIdsCKfS/giphy.gif)
