### ISSUE TITLE
Up/Down arrow keys stop working after a while

### ISSUE THREAD

**Issue by peternowell** [matt-curtis/Fluid-for-Sketch#90]
I have experienced on several occasions that my up and down arrow keys stop working after an extended session of using Fluid. Super frustrating for anyone using those keys to adjust values or move layers anywhere throughout the app. Solved by re-starting Sketch.

**Comment by matt-curtis** [comment]
I forgot to mention it in the Release Notes (which I'm updating now) but this should be fixed in the latest version, 1.7.3.

**Comment by peternowell** [comment]
Thanks, Matt. Will let you know if I experience it again.
