### ISSUE TITLE
Layer resize and fixed font size

### ISSUE THREAD

**Issue by jmarceli** [matt-curtis/Fluid-for-Sketch#91]
I'm referring to the `Constraint Demos.sketch` file (let say first canvas "The Sun"). When I resize entire canvas everything works as expected, but when I try to resize "Group" layer text inside that layer gets resized as well.

![image](https://cloud.githubusercontent.com/assets/4281333/13553367/6c3d1166-e387-11e5-9763-ac5b616bc7ba.png)

I don't know if it is possible but an option to disable text autoresize would be very helpful (e.g. creating reusable components with fluid layout).

**Comment by matt-curtis** [comment]
This is a default feature of Sketch, unfortunately it can't be easily overridden.
