### ISSUE TITLE
Constraints don't appear to work with Sketch 3.7

### ISSUE THREAD

**Issue by neilbilly** [matt-curtis/Fluid-for-Sketch#93]
Constraints appear to work ok in the new 'Symbols' page which 3.7 creates but when a symbol is then used on a regular page the constraints don't take affect.

**Comment by matt-curtis** [comment]
Thanks for filing this issue.

I'm unable to reproduce this issue...what kind of constraints? Have you tested on a new document?

**Comment by neilbilly** [comment]
Hi Matt

Yep I've tried with a new file in Sketch 3.7. Here's the steps I've tried:
1. New File
2. Insert an Artboard
3. Add a rectangle
4. Add text
5. Group the rectangle and text
6. Pin the group to the canvas (for example 0 pts from left, right and bottom)
7. Update Layout 
8. Pin the rectangle to the group (for example 0 pts from left, right and bottom)
9. Update Layout
10. Centre Horizontally the text to the group
11. Update Layout
12. Preview for iPhone 6, iPhone 6 Plus and iPhone SE with Fluid (all works as expected)
13. Create a symbol from the group
14. Preview for iPhone 6, iPhone 6 Plus and iPhone SE with Fluid - constraints stop working

Hope it helps,
Neil :)

**Comment by matt-curtis** [comment]
@neilbilly That's expected behavior - Symbols are now locked in size, and you cannot modify them unless you enter constraint edit mode.

**Comment by neilbilly** [comment]
@matt-curtis so are we saying that we can't use Symbols with Fluid (or any constraint plugin for that matter) at all or am I missing something? I hope I am it's a really useful plugin.

**Comment by matt-curtis** [comment]
That's correct. I'm sure there are ways to work around it, but as of now... no. :/ You can still position Symbols, but you can't affect their internal layout, unless you edit them and update their 'symbol artboard'

**Comment by neilbilly** [comment]
That's tragic @matt-curtis :( Such a good plugin.

**Comment by matt-curtis** [comment]
I know. The problem that arises is this - with Sketch's current symbol model, if a symbol's layout changes in one place, it should change everywhere (which makes sense). A 'responsive symbol' design doesn't make sense outside of a plugin like Fluid.

**Comment by neilbilly** [comment]
Got ya, that makes sense now. So I guess a plugin would have to duplicate the symbol and adapt that copy somehow for starters?

**Comment by matt-curtis** [comment]
Exactly. :)

**Comment by neilbilly** [comment]
You got any plans/time/desire to work on this? Or I wonder if we should raise it with Sketch as a feature request? What do think would be the best way forward?

**Comment by matt-curtis** [comment]
I'm not sure what Sketch is working on in this regard... (@bomberstudios :D)

However, as far as Fluid goes I don't see why this isn't possible, it just hasn't been discussed extensively yet. Just opened an issue for it - #95.

**Comment by neilbilly** [comment]
:+1:
