### ISSUE TITLE
Can't edit constraints 

### ISSUE THREAD

**Issue by ghost** [matt-curtis/Fluid-for-Sketch#94]
I'm pretty new to this plugin, however i cant seem to figure out how to edit constraints as it is always inactive. (refer to ss below) I'm using sketch 3.7 though

![screen shot 2016-04-18 at 5 52 11 pm](https://cloud.githubusercontent.com/assets/18528489/14600286/4c2f7296-058e-11e6-8d41-7725075339a2.png)

**Comment by matt-curtis** [comment]
Hello,

Have you clicked on the layers inside the artboard? Those are the ones with the constraints. The constraint inspector will appear 'inactive' until you click on a layer supporting/having constraints. Artboards cannot be constrained.

**Comment by ghost** [comment]
Ah! Cool, thanks much.
