### ISSUE TITLE
SVG 9-slice feature request

### ISSUE THREAD

**Issue by cbray** [matt-curtis/Fluid-for-Sketch#96]
Hi @matt-curtis - amazing work with the plugin! Unfortunately after getting very excited to find it, I believe that I had an unreasonable expectation. Everything works perfectly within Sketch, but for some reason I was really hoping that you'd be able to continue enforcing the constraints within an exported SVG. I'm trying to generate SVGs that maintain 9-slice scaling (like the same-named feature in Sketch itself, but that only works in the app as well and only applies to bitmaps).

From some digging it looks to be a wee bit tricky, but doable. [This guy](http://w3.eleqtriq.com/) seems to have figured out [the trick](http://w3.eleqtriq.com/2014/03/the-holy-grail-of-image-scaling/). Here's his [codepen example](http://codepen.io/DirkWeber/pen/mDiIs).

Is this something that the plugin could support? Thank you.

**Comment by matt-curtis** [comment]
Hello @cbray,

Thanks for opening an issue :)

That does sound cool, and I like the concept, but I'm not quite sure this is reasonably within the scope of Fluid. This seems like something better suited to a different plugin, or tackled on the HTML/CSS side of things.

**Comment by cbray** [comment]
Ok no worries - thanks!
